# Generated by Django 5.0.1 on 2024-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(choices=[('Wagner', 'Wagner'), ('Desert Ortho', 'Dweseert Ortho'), ('Georiga Eye Institute', 'Georiga Eye Institute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
