# Generated by Django 5.0.1 on 2024-01-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone_number_alter_client_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(choices=[('Wagner', 'Wagner'), ('Desert Ortho', 'Desert Ortho'), ('Georiga Eye Institute', 'Georiga Eye Institute')], max_length=100, unique=True),
        ),
    ]
