# Generated by Django 5.0.1 on 2024-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(choices=[('Wagner', 'Wagner'), ('Desert Ortho', 'Desert Ortho'), ('Georiga Eye Institute', 'Georiga Eye Institute'), ('Eyecare Of Atlanta', 'Eyecare Of Atlanta'), ('Manchester', 'Manchester')], max_length=100),
        ),
    ]
