# Generated by Django 5.0.1 on 2024-03-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verified_session',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
