# Generated by Django 5.0.1 on 2024-03-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_last_verified_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(choices=[('Wagner', 'Wagner'), ('Desert Ortho', 'Desert Ortho'), ('Georiga Eye Institute', 'Georiga Eye Institute'), ('Eyecare Of Atlanta', 'Eyecare Of Atlanta'), ('Manchester', 'Manchester'), ('Ortho Northeast', 'Ortho Northeast')], max_length=100),
        ),
    ]
